#!/bin/bash

set -e

FILE=$1
filename=$(basename "$FILE")
filename="${filename%.*}"
echo "optimising $FILE"
if [[ $FILE == *.asm ]]
then
	m4 -I../mpir/mpn/ $FILE | ./ajs -o "$filename"_optimised.asm "${@:2}"
elif [[ $FILE == *.as ]]
then
	../mpir/yasm/yasm -e -I../mpir/ $FILE | ./ajs -i -o "$filename"_optimised.asm "${@:2}"
elif [[ $FILE == *.c ]]
then
	gcc -S -O2 $FILE -o "$filename"_tmp.s
	./ajs "$filename"_tmp.s -o "$filename"_optimised.asm "${@:2}"
	rm "$filename"_tmp.s
fi
